### ISSUE TITLE
Remove automatic download of key/cert stuff from etcd

### ISSUE THREAD

**Issue by ryzy** [million12/docker-logstash-forwarder#2]
...and make it an option or sth - otherwise it seems like you cannot provide keys in another way, because they will be overridden by stuff from etcd anyway. Also, the etcd dir addr (now `/v2/keys/fwdkey`) is hardcoded.

See @odysseyscience fork: https://github.com/odysseyscience/logstash-forwarder

**Comment by pozgo** [comment]
fix on the way :)
