### ISSUE TITLE
/config/init/etcdcerts.sh

### ISSUE THREAD

**Issue by jwalton** [million12/docker-logstash-forwarder#3]
/config/init/etcdcerts.sh appears to be trying to download certificates and keys from the logstash server, from port 4001.

1) Secret keys (the .key file) should not be transferred over an insecure connection, such as `http`.
2) You're using the .crt file as both authentication and as the CA.  If an attacker executes a man-in-the-middle attack between your logstash-forwarder and your logstash nodes, they could feed you a fake self-signed certificate, then they could use that same certificate to set up a fake lumberjack server for you to connect to, and read/modify/forward your logs.  This is very insecure.
3) I assume this port 4001 thing is something custom you've written, since my logstash server doesn't have anything running on port 4001.  When I try to run this with my logstash server, this dies when it can't connect to port 4001.

**Comment by ryzy** [comment]
Thanks @jwalton 

This seems to be related to #2 - we plan to fix it during next project iteration (couple of weeks). Feel free to send PR if you'd like to work on it. Many thanks in advance!

**Comment by pozgo** [comment]
Fix on the way

**Comment by pozgo** [comment]
Fixed by last PR.
