### ISSUE TITLE
Build Failed: Branch ISSUE-221 no longer exists on LF offcial repo

### ISSUE THREAD

**Issue by pozgo** [million12/docker-logstash-forwarder#5]
Need to change to master branch and see if it is working without ssl errors.

**Comment by ryzy** [comment]
Eeee?

**Comment by pozgo** [comment]
Jest juz issue

Zjebali bo usuneli brancha z fixem do ssla :)

Wiec musze przebudowac na nowym branczu i przetestowac


Kind Regards
---


Przemyslaw Ozgo
mobile: +44 (0) 7740 814 002
email: przemyslaw@ozgo.info <mailto:przemyslaw@ozgo.info>
 <https://twitter.com/pozgo>
 <https://uk.linkedin.com/in/przemyslawozgo>
 <https://github.com/pozgo>
